server:
  port: 8888
spring:
  application:
    name: noone-server
    version: ${version}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/noone
    username: noone
    password: noone
jwt:
  secret: "u3SJYZOHd06qmX+AsSHKy9Mab8f3ciIWCQiqVvhsqlYZ9+HRmKp7akyzibfn1OdVMqCE2zjz1iHeWyj1Kg5zrg"
noone:
  plugin-registry:
    enabled: false
    catalog-url: ""